name: lotus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  phosphor_flutter: ^2.1.0
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  fuzzy: ^0.5.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/ttf/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/geist/ttf/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/geist/ttf/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/geist/ttf/Geist-Bold.ttf
          weight: 700
